# Generated by Django 3.0.5 on 2020-05-31 22:10

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


def create_flashcards(apps, schema_editor):
    Flashcard = apps.get_model("words", "Flashcard")
    Flashcard.objects.create(
        original_word="encouragement",
        translated_word="zachęta",
        original_language="en",
        translated_language="pl",
        dictionary_entry=r"[example_dictionary_entry]",
    )


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("original_word", models.CharField(max_length=50)),
                ("translated_word", models.CharField(max_length=100)),
                ("original_language", models.CharField(max_length=2)),
                ("translated_language", models.CharField(max_length=2)),
                ("dictionary_entry", django.contrib.postgres.fields.jsonb.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_flashcards),
    ]
