# Generated by Django 3.0.5 on 2020-05-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("learning", "0002_answers")]

    operations = [
        migrations.AddField(
            model_name="question",
            name="right_answer_id",
            field=models.IntegerField(blank=True, null=True),
        )
    ]
